final_project/Controllers/EmployerController.cs
using final_project.Models;
using final_project.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Data.Entity.Validation;

namespace final_project.Controllers
{
    public class EmployerController : Controller
    {
        finalprojectEntities db = new finalprojectEntities();
        // GET: Employer
        public ActionResult Index()
        {
            if (Session["EmployerID"] == null)
                return RedirectToAction("Login", "Account");
            
            string employerID = Session["EmployerID"].ToString();
            EMPLOYER employer = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == employerID)
                .SingleOrDefault();

            if (employer == null)
                return RedirectToAction("Login", "Account");
            
            return View(employer);
        }

        public ActionResult Edit(string id)
        {
            if (Session["EmployerID"] == null)
                return RedirectToAction("Login", "Account");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EMPLOYER employer = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == id)
                .SingleOrDefault();

            //這一段照理說應該要寫，但是http error 404 的頁面沒有排，盡量讓它不要出現 
            //if (employer == null)
            //{
            //    return HttpNotFound();
            //}

            DropDownListRepository listItem = new DropDownListRepository();
            ViewBag.genderList = new SelectList(listItem.getGenderListItem(), "Text", "Value");
            ViewBag.industryList = new SelectList(listItem.getIndustryListItem(), "Text", "Value");
            return View(employer);
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult SubmittedEdit(string clearCompany, string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var instructorToUpdate = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == id)
                .Single();

            if(TryUpdateModel(instructorToUpdate, "",
                new string[] { "Name", "PhotoRoute", "Gender", "Tel", "Birthday", "Acknowledge","COMPANY" }))
            {
                try
                {
                    //clearCompany傳進來的是要被clear的company的ID
                    if (clearCompany != null)
                    {
                        if (instructorToUpdate.COMPANY != null)
                        {
                            instructorToUpdate.COMPANY = null;
                        }

                        //加這一行，COMPANY資料表的那一筆才會刪掉
                        //如果以後要改搜尋，就註解調這一行，目前加這一行是因為不要讓company一直變超多
                        if (db.Companies.Find(clearCompany) != null)
                        {
                            db.Companies.Remove(db.Companies.Find(clearCompany));
                        }
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            DropDownListRepository listItem = new DropDownListRepository();
            ViewBag.genderList = new SelectList(listItem.getGenderListItem(), "Text", "Value");
            ViewBag.industryList = new SelectList(listItem.getIndustryListItem(), "Text", "Value");
            return View(instructorToUpdate);
        }

        public ActionResult CreateCompany(string id)
        {
            if (Session["EmployerID"] == null)
                return RedirectToAction("Login", "Account");

            EMPLOYER employer = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == id)
                .SingleOrDefault();

            if (employer == null)
            {
                return HttpNotFound();
            }
              if (employer.COMPANY != null)
            {
                return RedirectToAction("Index");
            }

            //edit HasCompany view bag
            //PopulateHasCompanyData(employer);
            DropDownListRepository listItem = new DropDownListRepository();
            ViewBag.industryList = new SelectList(listItem.getIndustryListItem(), "Text", "Value");
            return View(employer);
        }

        [HttpPost,ActionName("CreateCompany")]
        public ActionResult SubmittedCreateCompany(string id, COMPANY company)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var instructorToUpdate = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == id)
                .Single();
            
            if (TryUpdateModel(instructorToUpdate, "",
                new string[] {"COMPANY" }))
            {
                try
                {
                    instructorToUpdate.CompanyID = instructorToUpdate.COMPANY.CompanyID;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(instructorToUpdate);

        }

       
        public ActionResult UploadPicture(string id)
        {
            if (Session["EmployerID"] == null)
                return RedirectToAction("Login", "Account");

            ImageViewModels model = new ImageViewModels();
            EMPLOYER employer = db.Employers
                .Include(i => i.COMPANY)
                .Where(i => i.EmployerID == id)
                .SingleOrDefault();
            model.empID = employer.EmployerID;
            model.image = employer.ImageData;
            return View(model);
        }

        [HttpPost]
        public ActionResult UploadPicture(ImageViewModels imageViewModels)
        {
            HttpPostedFileBase file = Request.Files["PictureData"];
            ImageRepository service = new ImageRepository();

            EMPLOYER employer = db.Employers.Find(imageViewModels.empID);

            employer = service.UploadImageInDataBase(file, employer);
            if (ModelState.IsValid)
            {
                db.Entry(employer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(imageViewModels);
        }

        public ActionResult RetrieveImage(string id)
        {
            byte[] picture = GetImageFromDataBase(id);
            if (picture != null)
            {
                return File(picture, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public ActionResult AllWorksIndex(string sortOrder, string currentFilter, string searchstring, string clearSearchButton, int? page, bool? onePage)
        {
            if (Session["EmployerID"] == null)
                return RedirectToAction("Login", "Account");

            ViewBag.CurrentSort = sortOrder;
            ViewBag.WorkDateSortParm = sortOrder == "workDate" ? "workDate_desc" : "workDate";
            ViewBag.NumberOfWorkers = sortOrder == "numberOfWorkers" ? "numberOfWorkers_desc" : "numberOfWorkers";
            ViewBag.EstimatedCost = sortOrder == "estimatedCost" ? "estimatedCost_desc" : "estimatedCost";
            ViewBag.ActualCost = sortOrder == "actualCost" ? "actualCost_desc" : "actualCost";

            if (clearSearchButton != null)
            {
                searchstring = null;
            }
            else if (searchstring != null)
            {
                page = 1;
            }
            else
            {
                searchstring = currentFilter;
            }
            ViewBag.CurrentFilter = searchstring;

            string employerID = Session["EmployerID"].ToString();
            DateTime now = DateTime.Now;
            int nowHours = DateTime.Now.Hour;
            var dbWorks = db.Events
                .Where(e => e.EmployerID == employerID);

            if (dbWorks.Count() == 0)
                return RedirectToAction("NoUnfinishedEvent", "UnfinishedEvent");

            if (!String.IsNullOrEmpty(searchstring) &&
                    !(searchstring.Equals("徵人中")
                    || searchstring.Equals("已下架，但工作尚未開始")
                    || searchstring.Equals("工作中")
                    || searchstring.Equals("工作結束，未結清工資")
                    || searchstring.Equals("已結清工資")
                    || searchstring.Equals("全部")))
            {

                var selectedItems = dbWorks
                    .Where(s => s.Name.Contains(searchstring)
                        || s.EVENTTABs.Any(t => t.EventName.Contains(searchstring)));
                if (selectedItems.Count() != 0)
                {
                    dbWorks = selectedItems;
                }
                else
                {
                    ViewBag.selectedNothing = true;
                }
            }

final_project/Views/Employer/AllWorksIndex.cshtml
@model PagedList.IPagedList<final_project.Models.AllEventsViewModels>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/List3.css" rel="stylesheet" />

<h2>所有工作表列</h2>

<div class="dropdown">
    <button class="dropbtn">篩選</button>
    <div class="dropdown-content">
        <a class="a" href="@Url.Action("AllWorksIndex", "Employer", new {  currentFilter = "徵人中" })">
            徵人中
        </a>
        <a class="b" href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "已下架，但工作尚未開始" })">
            已下架，但工作尚未開始
        </a>
        <a class="c" href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "工作中" })">
            工作中
        </a>
        <a class="d" href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "工作結束，未結清工資" })">
            工作結束，未結清工資
        </a>
        <a class="e" href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "已結清工資" })">
            已結清工資
        </a>
        <a class="f" href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "全部" })">
            全部
        </a>
    </div>
</div>

<div class="dropdown list_2">
    <button class="dropbtn">排序(升冪/降冪)</button>
    <div class="dropdown-content">
        @Html.ActionLink("日期", "AllWorksIndex", new { sortOrder = ViewBag.WorkDateSortParm, currentFilter = ViewBag.CurrentFilter, onePage = ViewBag.onePage ? false : true }, new { @class = "sorting_a" })

        @Html.ActionLink("要求總人數", "AllWorksIndex", new { sortOrder = ViewBag.NumberOfWorkers, currentFilter = ViewBag.CurrentFilter, onePage = ViewBag.onePage ? false : true }, new { @class = "sorting_a" })

        @Html.ActionLink("總預算", "AllWorksIndex", new { sortOrder = ViewBag.EstimatedCost, currentFilter = ViewBag.CurrentFilter, onePage = ViewBag.onePage ? false : true }, new { @class = "sorting_a" })

        @Html.ActionLink("實際必須支付", "AllWorksIndex", new { sortOrder = ViewBag.ActualCost, currentFilter = ViewBag.CurrentFilter, onePage = ViewBag.onePage ? false : true }, new { @class = "sorting_a" })
    </div>
</div>

<br />

@using (Html.BeginForm("AllWorksIndex", "Employer", FormMethod.Get))
{
    //以下此段css來自：https://codepen.io/huange/pen/rbqsD
    <div class="wrap">
        <div class="search">
            <input type="text" class="searchTerm" id="searchstring" name="searchstring" type="search" placeholder="名稱、工作標籤">
            <button type="submit" class="searchButton" value="Search">
                <i class="fa fa-search"></i>
            </button>
        </div>
        @*暫時不做清空搜尋的功能，因為排版會很難看，而且input背用掉了，直接這樣寫繪出不來
            <input type="submit" name="clearSearchButton" value="清空搜尋" />*@
    </div>

}

<div class="dot_wrap">
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new {  currentFilter = "徵人中" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/a.png" />
        </a>
    </div>
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "已下架，但工作尚未開始" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/b.png" />
        </a>
    </div>
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "工作中" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/c.png" />
        </a>
    </div>
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "工作結束，未結清工資" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/d.png" />
        </a>
    </div>
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "已結清工資" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/e.png" />
        </a>
    </div>
    <div class="dot">
        <a href="@Url.Action("AllWorksIndex", "Employer", new { currentFilter = "全部" })" style="display:inline-block">
            <img class="dot_img" src="~/Pictures/f.png" />
        </a>
    </div>

</div>


<div class="dot_wrap">
    @if (ViewBag.selectedNothing != null)
    {
        <span style="font-size:120%; color:red;">拍謝！沒有你要搜尋的東西喔~~</span>
    }

</div>



 *以下金額僅大略估計，工時不滿一小時則四捨五入計算。
@*單頁瀏覽佳if判斷的原因：當沒有資料的時候，把pagesize = 0傳回controller，會有error。因為ToPagedList不吃為0的pagesize。*@
@if (Model.Count() != 0)
{
    <a class="single_page" href="@Url.Action("AllWorksIndex", "Employer", new {  sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, onePage = ViewBag.onePage })">
        @(ViewBag.onePage ? "單頁瀏覽" : "多頁瀏覽")
    </a>
}


<div class="row" style="margin:5px">

    @foreach (var item in Model)
    {
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <a href="@Url.Action("WorkDetails", "Employer",  new { id = item.EventID })" style="display:block;color:black;">
                <div class="selected_work">

                    <div style="background-color: @(item.statusColor);width:100%; float:top;height:5%;position: absolute;left:0,top:0"></div>
                    <div style="padding-top:8%;width:100%;padding:10%;">
                        @*常用的font family(英文，中文我不行)：https://www.w3schools.com/cssref/css_websafe_fonts.asp *@
                        <div class="work_name">
                            <div class=" animated-underline animated-underline_type4 news__link"
                                 style="  display: inline;
                                --uiAnimatedUnderlineWidth: var(--animatedUnderlineWidth, 100%);
                                --uiAnimatedUnderlineHeight: var(--animatedUnderlineHeight, 2px);
                                --uiAnimatedUnderlineBgColor: var(--animatedUnderlineBgColor,  @(item.statusColor));
                                --uiAnimatedUnderlinePositionX: var(--animatedUnderlinePositionX, left);
                                --uiAnimatedUnderlinePositionY: var(--animatedUnderlinePositionY, bottom);">
                                @item.Name
                            </div>
                        </div>

                        <div class="time">
                            <img src="~/Pictures/date.png" class="date_pic" />
                            @item.Date.ToShortDateString() <br />
                            &emsp; &emsp; &emsp;@Html.DisplayFor(m => item.Time_Start)
                            &ensp; ~  &ensp;
                            @Html.DisplayFor(m => item.Time_End)
                        </div>
                        <hr />
                        <div>
                            <img src="~/Pictures/blue_person.jpg" class="person_pic" />
                            @Html.DisplayFor(m => item.NumberOfWorkers)
                        </div>
                        <hr />
                        <div>
                            <img src="~/Pictures/cost3.png" class="cost_pic" />
                            <div style=" display: inline-block;">
                                總預算： @Html.DisplayFor(m => item.EstimatedCost) <br>
                                實際支付： @Html.DisplayFor(m => item.ActualCost)
                            </div>

                        </div>



                    </div>

                </div>
            </a>
        </div>
    }

</div>


@if (ViewBag.onePage)
{
    <br />
    @:第 @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber ) 頁，總共 @Model.PageCount 頁
    @Html.PagedListPager(Model, page => Url.Action("AllWorksIndex",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    new PagedListRenderOptions
    {
        LinkToFirstPageFormat = "<< 第一頁",
        LinkToPreviousPageFormat = "< 前一頁",
        LinkToNextPageFormat = "後一頁 >",
        LinkToLastPageFormat = "最末頁 >>"
    })
}

final_project/Views/Employer/CreateCompany.cshtml
@model final_project.Models.EMPLOYER

@{
    ViewBag.Title = "CreateCompany";
}

<h2>CreateCompany</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>EMPLOYER</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EmployerID)
    @Html.HiddenFor(model => model.Name)
    @Html.HiddenFor(model => model.Gender)
    @Html.HiddenFor(model => model.Tel)
    @Html.HiddenFor(model => model.Birthday)
    @Html.HiddenFor(model => model.Acknowledge)

    @Html.TextBoxFor(m => m.COMPANY.CompanyID, new { @type = "hidden", @Value = DateTime.Now.ToString("yyyyMMddHHmmssfff") })


    <div class="form-group">
        @Html.LabelFor(model => model.COMPANY.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.COMPANY.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.COMPANY.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.COMPANY.Tel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.COMPANY.Tel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.COMPANY.Tel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.COMPANY.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.COMPANY.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.COMPANY.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.COMPANY.Industry, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("COMPANY.Industry", ViewBag.industryList as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.COMPANY.Industry, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.COMPANY.Intro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.COMPANY.Intro, new { @class = "ckeditor", placeholder = "Intro" })
            @Html.ValidationMessageFor(model => model.COMPANY.Intro, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <table style="margin-left:30%">
            <tr>
                <td><input type="submit" value="儲存" class="btn btn-default" /></td>
                <td> @Html.ActionLink("回上一頁", "Index", null, new { @class = "underlined underlined--gradient" })</td>
            </tr>
        </table>
    </div>
</div>
}

@section Scripts {
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/ckeditor/adapters/jquery.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

final_project/Views/Employer/EndEvent.cshtml
@model final_project.Models.EVENT

@if (@ViewBag.finishable)
{
    using (Html.BeginForm())
    {
        <input type="hidden" name="workerId" value="@ViewBag.id" />
        <input type="hidden" name="applierId" value="@ViewBag.finishable" />
        <input type="submit" />
    }
}
else
{
    @:不好意思，有還沒有案finish，你不能按
}

final_project/Views/Employer/UploadPicture.cshtml
@model final_project.Models.ImageViewModels

<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
        }
    }
</script>
<h2>上傳大頭貼</h2>
@using (Html.BeginForm("UploadPicture", "Employer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*@Html.AntiForgeryToken()*@
    @Html.HiddenFor(m => m.empID)



    <div class="form-group">
        不傳照片，按下儲存，原本的頭貼會不見喔！ (其實不想擺頭貼，也沒關係啦 (￣﹃￣)，只是寫網頁的同學會很難過，枉費她寫了著個功能WW  )
        <div class="col-md-10">
            <input type="file" name="PictureData" id="PictureData" onchange="fileCheck(this);" />
            @Html.ValidationMessageFor(model => model.image)
        </div>
    </div>

    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="btn btn-default" />
            </div>
        </div>*@

    <div class="form-group">
        <table style="float:left; margin:10px; margin-left:30%">
            <tr>
                <td><input type="submit" value="儲存" class="btn btn-default" /></td>
                <td> @Html.ActionLink("回上一頁", "Index", null, new { @class = "underlined underlined--gradient" })</td>
            </tr>
        </table>
    </div>
}
@*<div>
        @Html.ActionLink("Back to List", "Index", new { @class = "underlined underlined--gradient" })
    </div>*@